### ISSUE TITLE
Where is the code that implements asfyaml

### ISSUE THREAD

**Issue by Xuanwo** [apache/infrastructure-asfyaml#12]
Hello, thank you very much for creating this guide. However, I am still confused about some specific options, such as the `category` for the `discussion` event. Where can I find the code that implements asfyaml? Perhaps we should also document it?

**Comment by raboof** [comment]
That code is not public, but if you have access you can find it at https://github.com/apache/infrastructure-p6/blob/production/modules/gitbox/files/asfgit/package/asfyaml.py

**Comment by Xuanwo** [comment]
> That code is not public, but if you have access you can find it at [apache/infrastructure-p6@`production`/modules/gitbox/files/asfgit/package/asfyaml.py](https://github.com/apache/infrastructure-p6/blob/production/modules/gitbox/files/asfgit/package/asfyaml.py?rgh-link-date=2024-10-18T10%3A33%3A41Z)

Thank you for this!
