### ISSUE TITLE
feature request - allow supporting auto-merge

### ISSUE THREAD

**Issue by mistercrunch** [apache/infrastructure-asfyaml#8]
For the Superset project, we'd love to turn on the auto-merge GitHub feature. It allows setting individual PRs to auto-merge once all criteria are met (all CI checks pass + review-related criteria met)

<img width="814" alt="Screenshot 2024-05-06 at 11 47 36 AM" src="https://github.com/apache/infrastructure-asfyaml/assets/487433/cc993e22-b56e-4a6a-bcea-4422019c423f">

Let me know if there's a way for me to contribute the feature as I don't see the source code for how the .asf.yml is applied.

**Comment by Humbedooh** [comment]
As per the last time this was requested ( https://issues.apache.org/jira/browse/INFRA-23647 ), the project still needs to speak to VP Legal about this. Our current policy is to not allow auto-merge for provenance reasons.
