### ISSUE TITLE
Remove staging website on branch deletion

### ISSUE THREAD

**Issue by vy** [apache/infrastructure-asfyaml#9]
INFRA doesn't react to the deletion of branches used to serve websites through `.asf.yaml` entries. See [INFRA-25716](https://issues.apache.org/jira/browse/INFRA-25716) for the background. As indicated by @Humbedooh in [this #asfinfra Slack thread](https://the-asf.slack.com/archives/CBX4TSBQ8/p1715206655265539?thread_ts=1715191720.431459&cid=CBX4TSBQ8), INFRA finds the following approach plausible:

When a branch, containing an `.asf.yaml` with a `staging.profile: <profile>` entry, is deleted, `<project>-<profile>.staged.apache.org` will be deleted too.

I would appreciate it if INFRA can implement this feature.

**Comment by Humbedooh** [comment]
For staging sites at the top level ( foo.staged.apache.org ), this is already the case (we overlooked that this had been implemented last year, apologies), so if you delete a branch, it should disappear in the nightly cleanup.

**Comment by vy** [comment]
@Humbedooh, is this only available for `staging.profile` that are different than `~`, or does it also work with `staging.subdir` too?

**Comment by Humbedooh** [comment]
Currently, it only works for top level sites, so foo.staged.a.o, whereas a sub-checkout in foo.staged.a.o/bar/ would not be subject to the same pruning. We can expand that to go into the deeper directory levels, especially as I just realized yesterday that we already have this system in place.

**Comment by vy** [comment]
That would be great.
Is this ticket good enough?
Or shall I adapt its description accordingly?

**Comment by Humbedooh** [comment]
I have modified the pruning process to recurse into all subdirs of staging sites, which should help get rid of any sub-sites that are stale. Is there anything else we need to look at?

**Comment by Humbedooh** [comment]
To clarify, nothing is currently needed in .asf.yaml for this to work, the process checks for missing branches and if found, removes the stale staging site.

**Comment by vy** [comment]
@Humbedooh, so... `logging.staged.apache.org/log4j/tools-0.9.0` should be cleaned up tonight, right?

**Comment by Humbedooh** [comment]
It should already be cleaned up, the run from this morning cleaned up a bunch of the stale sub-sites:
```
Removing /www/logging-clean/content/log4j, branch no longer present on remote
Removing /www/logging-parent/content/logging-parent, branch no longer present on remote
Removing /www/logging/content/logging-parent-, branch no longer present on remote
Removing /www/logging/content/logging-parent-11.1.0, branch no longer present on remote
Removing /www/logging/content/logging-parent-11.0.0, branch no longer present on remote
Removing /www/logging/content/logging-parent-11.0.0-test2, branch no longer present on remote
Removing /www/logging/content/log4j/tools-0.9.0, branch no longer present on remote
```

**Comment by vy** [comment]
Thanks! :bow:
